version: '3.8'

services:
  horizon_server:
    container_name: horizon_server
    image: python:3.8-alpine
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "apk add  git bash python3 curl tzdata pkgconfig mysql-dev && \
             cp /usr/share/zoneinfo/Asia/Kolkata /etc/localtime && \
             if [ -d 'horizon' ]; then cd horizon && git pull && cd ..; else git clone -b npi https://github.com/danish-mar/horizon.git; fi && \
             cd horizon && \
             python -m venv .venv && \
             source .venv/bin/activate && \
             pip install -r requirements.txt && \
             export FLASK_ENV= dockerconfig && \
             flask run --host=0.0.0.0"

    ports:
      - "5000:5000"
    depends_on:
      - nebula_server
      - shinobi

  shinobi:
    container_name: shinobi
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /docker/shinobi:/data

  nebula_server:
    container_name: nebula_server
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: nahida@dendro123
      MYSQL_DATABASE: nebula
      TZ: Asia/Kolkata

    ports:
      - "3306:3306"
    volumes:
      - /docker/database_mysql:/var/lib/mysql

volumes:
  db_data:
